#+TITLE: Examples of code blocks with ob-julia
#+AUTHOR: Frédéric Santos
#+OPTIONS: todo:t
#+STARTUP: noindent

* IN-PROGRESS External evaluation
If ~:session~ is not specified (or equal to ~none~), then the code block is evaluated through an external process.

** IN-PROGRESS With ~:results output~
Simple (numeric or text) ~:results output~ are supported:

#+BEGIN_SRC julia :results output :exports both
println("Hello world!")
#+END_SRC

#+RESULTS:
: Hello world!

#+begin_src julia :results output :exports both
print(2+3)
#+end_src

#+RESULTS:
: 5

More complex outputs such as graphic files are still to be supported.

** IN-PROGRESS With ~:results value~
Basic Julia types (arrays, dictionaries and tuples) are supported. DataFrames, which are a non-native data structure, have some kind of basic support, but are still to be improved. Some examples are given below.

*** DONE Arrays
    CLOSED: [2020-10-06 mar. 18:32]
#+begin_src julia :results value :exports both
a = [1 2 3 4]
a
#+end_src

#+RESULTS:
| 1 | 2 | 3 | 4 |

*** DONE Dictionaries
    CLOSED: [2020-10-06 mar. 18:33]
#+begin_src julia :results value :exports both
d = Dict("Emacs" => "awesome", "Julia" => "nice")
d
#+end_src

#+RESULTS:
| Julia | nice    |
| Emacs | awesome |

*** DONE Tuples
    CLOSED: [2020-10-06 mar. 18:35]
#+begin_src julia :results value :exports both
t = ("org", "mode", "is", "great")
t
#+end_src

#+RESULTS:
| org  |
| mode |
| is   |
| bing |

*** IN-PROGRESS DataFrames
A basic ~value~ display is possible. However, column names and row names are not well supported yet.

#+begin_src julia :results value :exports both
dtf = DataFrame(                 
 [8.04   9.14  7.46   6.58;    
  6.95   8.14  6.77   5.76;   
  7.58   8.74  12.74  7.71;   
  8.81   8.77  7.11   8.84;   
  8.33   9.26  7.81   8.47])
rename!(dtf, [:a, :b, :c, :d])
dtf
#+end_src

#+RESULTS:
|    a |    b |     c |    d |
| 8.04 | 9.14 |  7.46 | 6.58 |
| 6.95 | 8.14 |  6.77 | 5.76 |
| 7.58 | 8.74 | 12.74 | 7.71 |
| 8.81 | 8.77 |  7.11 | 8.84 |
| 8.33 | 9.26 |  7.81 | 8.47 |

* TODO Evaluation within a session
Evaluation of several code blocks within a given session is not supported yet.

#+BEGIN_SRC julia :results output :session *juliasession* :exports both
println("Hello world!")
#+END_SRC

#+RESULTS:
: You want to use session *juliasession* but this does not work yet :-)
